site_name: Network Notes
site_url: https://bzoel.io
site_author: Billy Zoellers
site_description: Reflections of an IT Infrastructure Consultant learning about automation, security, and routing/switching
repo_name: bzoel/bzoel.github.io
repo_url: https://github.com/bzoel/bzoel.github.io
edit_uri: blob/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides/
  icon:
    logo: fa5/logo
    repo: fontawesome/brands/github
    admonition:
      tip: fontawesome/regular/lightbulb
      note: fontawesome/regular/note-sticky
  favicon: assets/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to system preference
      primary: custom
      accent: custom
  features:
    - toc.follow
    # - toc.integrate
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.instant
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.suggest
    - content.action.view
    - content.tooltips
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bzoel
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/billyzoellers
    - icon: fontawesome/brands/github
      link: https://github.com/bzoel
  generator: false
copyright: Copyright &copy; 2023 Billy Zoellers
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
plugins:
  - search
  - social
  - meta
  # - optimize
  - glightbox:
      skip_classes:
        - cert
  - git-revision-date-localized
  - git-committers:
      enabled: false
      repository: bzoel/bzoel.github.io
      branch: main
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
      post_readtime: true
      archive: false
      archive_name: Posts
      archive_date_format: MMMM YYYY
      archive_url_date_format: YYYY
      archive_url_format: "archive/{date}"
      categories: false
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
nav:
  - Home: index.md
  - About: about.md
  - Cert Studies:
    - CCIE Enterprise:
      - studies/ccie-ei/index.md
      - DMVPN: studies/ccie-ei/dmvpn.md
      - EIGRP: studies/ccie-ei/eigrp.md
      - OSPF: studies/ccie-ei/ospf.md
      - MPLS/L3VPN: studies/ccie-ei/mpls.md
      - Multicast: studies/ccie-ei/multicast.md
      - SD-Access: studies/ccie-ei/sdaccess.md
      - BGP: studies/ccie-ei/bgp.md
    - CCNP ROUTE:
      - studies/ccnp-route/1-network-prin.md
      - studies/ccnp-route/4-vpn-tech.md
      - studies/ccnp-route/5-infra-security.md
      - studies/ccnp-route/eigrp.md
      - studies/ccnp-route/vrf-lite.md
    - ENSDWI:
      - studies/ensdwi/1-architecture.md
      - studies/ensdwi/2-controller-deployment.md
      - studies/ensdwi/3-router-deployment.md
      - studies/ensdwi/4-policies.md
      - studies/ensdwi/5-security-qos.md
      - studies/ensdwi/6-management-operations.md